/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_win_main (void);
GtkWidget* create_win_chat (void);
GtkWidget* create_win_prefs (void);
GtkWidget* create_win_desc (void);
GtkWidget* create_win_conf_wizard (void);
GtkWidget* create_win_msg_send (void);
GtkWidget* create_win_msg_recv (void);
GtkWidget* create_win_edit (void);
GtkWidget* create_win_about (void);
