/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_win_main (void)
{
  GtkWidget *win_main;
  GtkWidget *vbox1;
  GtkWidget *user_tree_scroll;
  GtkWidget *user_tree;
  GtkWidget *hbox_buttons;
  GtkWidget *menu_btn;
  GtkWidget *image2;
  GtkWidget *space_1;
  GtkWidget *status_btn;
  GtkWidget *image_status_button;

  win_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_main, "win_main");
  gtk_widget_set_size_request (win_main, 200, 300);
  gtk_container_set_border_width (GTK_CONTAINER (win_main), 1);
  gtk_window_set_title (GTK_WINDOW (win_main), "glen");
  gtk_window_set_default_size (GTK_WINDOW (win_main), 250, 400);
  gtk_window_set_gravity (GTK_WINDOW (win_main), GDK_GRAVITY_NORTH_EAST);

  vbox1 = gtk_vbox_new (FALSE, 2);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (win_main), vbox1);

  user_tree_scroll = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (user_tree_scroll, "user_tree_scroll");
  gtk_widget_show (user_tree_scroll);
  gtk_box_pack_start (GTK_BOX (vbox1), user_tree_scroll, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (user_tree_scroll), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (user_tree_scroll), GTK_SHADOW_ETCHED_IN);

  user_tree = gtk_tree_view_new ();
  gtk_widget_set_name (user_tree, "user_tree");
  gtk_widget_show (user_tree);
  gtk_container_add (GTK_CONTAINER (user_tree_scroll), user_tree);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (user_tree), FALSE);

  hbox_buttons = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox_buttons, "hbox_buttons");
  gtk_widget_show (hbox_buttons);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox_buttons, FALSE, TRUE, 0);
  gtk_widget_set_size_request (hbox_buttons, -1, 28);

  menu_btn = gtk_button_new ();
  gtk_widget_set_name (menu_btn, "menu_btn");
  gtk_widget_show (menu_btn);
  gtk_box_pack_start (GTK_BOX (hbox_buttons), menu_btn, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (menu_btn, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (menu_btn), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (menu_btn), FALSE);

  image2 = create_pixmap (win_main, "glen/menu-tlen.png");
  gtk_widget_set_name (image2, "image2");
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (menu_btn), image2);

  space_1 = gtk_label_new ("");
  gtk_widget_set_name (space_1, "space_1");
  gtk_widget_show (space_1);
  gtk_box_pack_start (GTK_BOX (hbox_buttons), space_1, TRUE, FALSE, 0);

  status_btn = gtk_button_new ();
  gtk_widget_set_name (status_btn, "status_btn");
  gtk_widget_show (status_btn);
  gtk_box_pack_start (GTK_BOX (hbox_buttons), status_btn, FALSE, FALSE, 0);
  gtk_button_set_relief (GTK_BUTTON (status_btn), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (status_btn), FALSE);

  image_status_button = create_pixmap (win_main, "glen/status-unavail.png");
  gtk_widget_set_name (image_status_button, "image_status_button");
  gtk_widget_show (image_status_button);
  gtk_container_add (GTK_CONTAINER (status_btn), image_status_button);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_main, win_main, "win_main");
  GLADE_HOOKUP_OBJECT (win_main, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (win_main, user_tree_scroll, "user_tree_scroll");
  GLADE_HOOKUP_OBJECT (win_main, user_tree, "user_tree");
  GLADE_HOOKUP_OBJECT (win_main, hbox_buttons, "hbox_buttons");
  GLADE_HOOKUP_OBJECT (win_main, menu_btn, "menu_btn");
  GLADE_HOOKUP_OBJECT (win_main, image2, "image2");
  GLADE_HOOKUP_OBJECT (win_main, space_1, "space_1");
  GLADE_HOOKUP_OBJECT (win_main, status_btn, "status_btn");
  GLADE_HOOKUP_OBJECT (win_main, image_status_button, "image_status_button");

  return win_main;
}

GtkWidget*
create_win_chat (void)
{
  GtkWidget *win_chat;
  GtkWidget *vbox;
  GtkWidget *scroll_output;
  GtkWidget *hbox5;
  GtkWidget *eventbox_typing;
  GtkWidget *image_typing;
  GtkWidget *scroll_input;
  GtkWidget *input;
  GtkWidget *hbox_bottom;
  GtkWidget *clear_btn;
  GtkWidget *image6;
  GtkWidget *enter_sends_btn;
  GtkWidget *image7;
  GtkWidget *emote_btn;
  GtkWidget *image8;
  GtkWidget *a;
  GtkWidget *send_btn;
  GtkWidget *alignment1;
  GtkWidget *hbox3;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *close_btn;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_chat = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_chat, "win_chat");
  gtk_widget_set_size_request (win_chat, 300, 280);
  gtk_widget_set_events (win_chat, GDK_VISIBILITY_NOTIFY_MASK);
  gtk_window_set_title (GTK_WINDOW (win_chat), "win_chat");
  gtk_window_set_default_size (GTK_WINDOW (win_chat), 400, 250);

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox, "vbox");
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (win_chat), vbox);
  gtk_container_set_border_width (GTK_CONTAINER (vbox), 2);

  scroll_output = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scroll_output, "scroll_output");
  gtk_widget_show (scroll_output);
  gtk_box_pack_start (GTK_BOX (vbox), scroll_output, TRUE, TRUE, 1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scroll_output), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scroll_output), GTK_SHADOW_ETCHED_IN);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox), hbox5, FALSE, TRUE, 0);
  gtk_widget_set_size_request (hbox5, -1, 16);

  eventbox_typing = gtk_event_box_new ();
  gtk_widget_set_name (eventbox_typing, "eventbox_typing");
  gtk_widget_show (eventbox_typing);
  gtk_box_pack_start (GTK_BOX (hbox5), eventbox_typing, FALSE, TRUE, 0);

  image_typing = create_pixmap (win_chat, NULL);
  gtk_widget_set_name (image_typing, "image_typing");
  gtk_widget_show (image_typing);
  gtk_container_add (GTK_CONTAINER (eventbox_typing), image_typing);

  scroll_input = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scroll_input, "scroll_input");
  gtk_widget_show (scroll_input);
  gtk_box_pack_start (GTK_BOX (vbox), scroll_input, FALSE, FALSE, 1);
  gtk_widget_set_size_request (scroll_input, -1, 50);
  GTK_WIDGET_UNSET_FLAGS (scroll_input, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scroll_input), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scroll_input), GTK_SHADOW_ETCHED_IN);

  input = gtk_text_view_new ();
  gtk_widget_set_name (input, "input");
  gtk_widget_show (input);
  gtk_container_add (GTK_CONTAINER (scroll_input), input);
  GTK_WIDGET_SET_FLAGS (input, GTK_CAN_DEFAULT);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (input), GTK_WRAP_WORD);
  gtk_text_view_set_left_margin (GTK_TEXT_VIEW (input), 1);
  gtk_text_view_set_right_margin (GTK_TEXT_VIEW (input), 1);

  hbox_bottom = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox_bottom, "hbox_bottom");
  gtk_widget_show (hbox_bottom);
  gtk_box_pack_start (GTK_BOX (vbox), hbox_bottom, FALSE, TRUE, 2);
  gtk_widget_set_size_request (hbox_bottom, -1, 28);

  clear_btn = gtk_button_new ();
  gtk_widget_set_name (clear_btn, "clear_btn");
  gtk_widget_show (clear_btn);
  gtk_box_pack_start (GTK_BOX (hbox_bottom), clear_btn, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, clear_btn, "Wyczy\305\233\304\207 okno rozmowy", NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (clear_btn), FALSE);

  image6 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image6, "image6");
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (clear_btn), image6);

  enter_sends_btn = gtk_toggle_button_new ();
  gtk_widget_set_name (enter_sends_btn, "enter_sends_btn");
  gtk_widget_show (enter_sends_btn);
  gtk_box_pack_start (GTK_BOX (hbox_bottom), enter_sends_btn, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, enter_sends_btn, "Je\305\233li przycisk jest wci\305\233ni\304\231ty, klawisz Enter wysy\305\202a wiadomo\305\233\304\207", NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (enter_sends_btn), FALSE);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (enter_sends_btn), TRUE);

  image7 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image7, "image7");
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (enter_sends_btn), image7);

  emote_btn = gtk_button_new ();
  gtk_widget_set_name (emote_btn, "emote_btn");
  gtk_widget_show (emote_btn);
  gtk_box_pack_start (GTK_BOX (hbox_bottom), emote_btn, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, emote_btn, "Wstaw emotikon\304\231", NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (emote_btn), FALSE);

  image8 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image8, "image8");
  gtk_widget_show (image8);
  gtk_container_add (GTK_CONTAINER (emote_btn), image8);

  a = gtk_label_new ("");
  gtk_widget_set_name (a, "a");
  gtk_widget_show (a);
  gtk_box_pack_start (GTK_BOX (hbox_bottom), a, TRUE, TRUE, 0);
  gtk_widget_set_size_request (a, 64, -1);
  gtk_widget_set_sensitive (a, FALSE);

  send_btn = gtk_button_new ();
  gtk_widget_set_name (send_btn, "send_btn");
  gtk_widget_show (send_btn);
  gtk_box_pack_start (GTK_BOX (hbox_bottom), send_btn, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, send_btn, "Wy\305\233lij wiadomo\305\233\304\207 do rozm\303\263wcy", NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (send_btn), FALSE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (send_btn), alignment1);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox3);

  image1 = gtk_image_new_from_stock ("gnome-stock-mail-snd", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image1, "image1");
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox3), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic ("_Wy\305\233lij");
  gtk_widget_set_name (label2, "label2");
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox3), label2, FALSE, FALSE, 0);

  close_btn = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (close_btn, "close_btn");
  gtk_widget_show (close_btn);
  gtk_box_pack_start (GTK_BOX (hbox_bottom), close_btn, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, close_btn, "Zamknij okno", NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (close_btn), FALSE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_chat, win_chat, "win_chat");
  GLADE_HOOKUP_OBJECT (win_chat, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (win_chat, scroll_output, "scroll_output");
  GLADE_HOOKUP_OBJECT (win_chat, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (win_chat, eventbox_typing, "eventbox_typing");
  GLADE_HOOKUP_OBJECT (win_chat, image_typing, "image_typing");
  GLADE_HOOKUP_OBJECT (win_chat, scroll_input, "scroll_input");
  GLADE_HOOKUP_OBJECT (win_chat, input, "input");
  GLADE_HOOKUP_OBJECT (win_chat, hbox_bottom, "hbox_bottom");
  GLADE_HOOKUP_OBJECT (win_chat, clear_btn, "clear_btn");
  GLADE_HOOKUP_OBJECT (win_chat, image6, "image6");
  GLADE_HOOKUP_OBJECT (win_chat, enter_sends_btn, "enter_sends_btn");
  GLADE_HOOKUP_OBJECT (win_chat, image7, "image7");
  GLADE_HOOKUP_OBJECT (win_chat, emote_btn, "emote_btn");
  GLADE_HOOKUP_OBJECT (win_chat, image8, "image8");
  GLADE_HOOKUP_OBJECT (win_chat, a, "a");
  GLADE_HOOKUP_OBJECT (win_chat, send_btn, "send_btn");
  GLADE_HOOKUP_OBJECT (win_chat, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (win_chat, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (win_chat, image1, "image1");
  GLADE_HOOKUP_OBJECT (win_chat, label2, "label2");
  GLADE_HOOKUP_OBJECT (win_chat, close_btn, "close_btn");
  GLADE_HOOKUP_OBJECT_NO_REF (win_chat, tooltips, "tooltips");

  gtk_widget_grab_focus (input);
  gtk_widget_grab_default (input);
  return win_chat;
}

GtkWidget*
create_win_prefs (void)
{
  GtkWidget *win_prefs;
  GdkPixbuf *win_prefs_icon_pixbuf;
  GtkWidget *vbox2;
  GtkWidget *notebook;
  GtkWidget *vbox7;
  GtkWidget *frame7;
  GtkWidget *alignment16;
  GtkWidget *table5;
  GtkWidget *label48;
  GtkWidget *label47;
  GtkWidget *entry_id;
  GtkWidget *entry_pass;
  GtkWidget *label46;
  GtkWidget *label41;
  GtkWidget *label49;
  GtkWidget *label42;
  GtkWidget *vbox9;
  GtkWidget *frame10;
  GtkWidget *alignment19;
  GtkWidget *table8;
  GtkWidget *checkbutton_emots;
  GtkWidget *label_emote_set;
  GtkWidget *comboboxentry_emote_set;
  GtkWidget *label58;
  GtkWidget *label43;
  GtkWidget *vbox8;
  GtkWidget *frame8;
  GtkWidget *alignment17;
  GtkWidget *table6;
  GtkWidget *checkbutton_autoaway;
  GtkWidget *label_aa2;
  GtkObject *spinbutton_away_time_adj;
  GtkWidget *spinbutton_away_time;
  GtkObject *spinbutton_bbl_time_adj;
  GtkWidget *spinbutton_bbl_time;
  GtkWidget *label_aa11;
  GtkWidget *label_aa1;
  GtkWidget *label_aa22;
  GtkWidget *checkbutton_autoaway_desc;
  GtkWidget *label50;
  GtkWidget *frame9;
  GtkWidget *alignment18;
  GtkWidget *table9;
  GtkWidget *radiobutton_start_status;
  GSList *radiobutton_start_status_group = NULL;
  GtkWidget *comboboxentry_start_status;
  GtkWidget *radiobutton_status_save;
  GtkWidget *checkbutton_desc_save;
  GtkWidget *checkbutton_save_desc_at_exit;
  GtkWidget *label57;
  GtkWidget *label44;
  GtkWidget *vbox10;
  GtkWidget *hbox188;
  GtkWidget *label60;
  GtkWidget *entry_browser;
  GtkWidget *label61;
  GtkWidget *label45;
  GtkWidget *hbox4;
  GtkWidget *label_bottom;
  GtkWidget *button_cancel;
  GtkWidget *button_accept;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_prefs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_prefs, "win_prefs");
  gtk_container_set_border_width (GTK_CONTAINER (win_prefs), 12);
  gtk_window_set_title (GTK_WINDOW (win_prefs), "Ustawienia");
  gtk_window_set_resizable (GTK_WINDOW (win_prefs), FALSE);
  win_prefs_icon_pixbuf = create_pixbuf ("glen/status-avail.png");
  if (win_prefs_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (win_prefs), win_prefs_icon_pixbuf);
      gdk_pixbuf_unref (win_prefs_icon_pixbuf);
    }

  vbox2 = gtk_vbox_new (FALSE, 12);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (win_prefs), vbox2);

  notebook = gtk_notebook_new ();
  gtk_widget_set_name (notebook, "notebook");
  gtk_widget_show (notebook);
  gtk_box_pack_start (GTK_BOX (vbox2), notebook, TRUE, TRUE, 0);
  gtk_widget_set_size_request (notebook, 500, 350);

  vbox7 = gtk_vbox_new (FALSE, 12);
  gtk_widget_set_name (vbox7, "vbox7");
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (notebook), vbox7);
  gtk_container_set_border_width (GTK_CONTAINER (vbox7), 12);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame7, "frame7");
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (vbox7), frame7, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame7), GTK_SHADOW_NONE);

  alignment16 = gtk_alignment_new (0, 0.5, 0.1, 1);
  gtk_widget_set_name (alignment16, "alignment16");
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (frame7), alignment16);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment16), 0, 0, 12, 0);

  table5 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table5, "table5");
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (alignment16), table5);
  gtk_container_set_border_width (GTK_CONTAINER (table5), 6);
  gtk_table_set_row_spacings (GTK_TABLE (table5), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table5), 6);

  label48 = gtk_label_new ("Has\305\202o:");
  gtk_widget_set_name (label48, "label48");
  gtk_widget_show (label48);
  gtk_table_attach (GTK_TABLE (table5), label48, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label48), 0, 0.5);

  label47 = gtk_label_new ("Identyfikator:");
  gtk_widget_set_name (label47, "label47");
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table5), label47, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label47), 0, 0.5);

  entry_id = gtk_entry_new ();
  gtk_widget_set_name (entry_id, "entry_id");
  gtk_widget_show (entry_id);
  gtk_table_attach (GTK_TABLE (table5), entry_id, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_id, 200, -1);
  gtk_tooltips_set_tip (tooltips, entry_id, "Tw\303\263j login w sieci Tlen.pl", NULL);

  entry_pass = gtk_entry_new ();
  gtk_widget_set_name (entry_pass, "entry_pass");
  gtk_widget_show (entry_pass);
  gtk_table_attach (GTK_TABLE (table5), entry_pass, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_pass, 200, -1);
  gtk_tooltips_set_tip (tooltips, entry_pass, "Je\305\233li nie podasz has\305\202a b\304\231dziesz o nie pytany przy ka\305\274dym uruchomieniu programu", NULL);
  gtk_entry_set_visibility (GTK_ENTRY (entry_pass), FALSE);

  label46 = gtk_label_new ("<b>Login</b>");
  gtk_widget_set_name (label46, "label46");
  gtk_widget_show (label46);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label46);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  label41 = gtk_label_new ("Identyfikacja");
  gtk_widget_set_name (label41, "label41");
  gtk_widget_show (label41);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), label41);

  label49 = gtk_label_new ("<b><span size=\"x-large\">Tu co\305\233 b\304\231dzie :)</span></b>");
  gtk_widget_set_name (label49, "label49");
  gtk_widget_show (label49);
  gtk_container_add (GTK_CONTAINER (notebook), label49);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  label42 = gtk_label_new ("Okno g\305\202\303\263wne");
  gtk_widget_set_name (label42, "label42");
  gtk_widget_show (label42);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), label42);

  vbox9 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox9, "vbox9");
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (notebook), vbox9);
  gtk_container_set_border_width (GTK_CONTAINER (vbox9), 12);

  frame10 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame10, "frame10");
  gtk_widget_show (frame10);
  gtk_box_pack_start (GTK_BOX (vbox9), frame10, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame10), GTK_SHADOW_NONE);

  alignment19 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment19, "alignment19");
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (frame10), alignment19);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment19), 0, 0, 12, 0);

  table8 = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table8, "table8");
  gtk_widget_show (table8);
  gtk_container_add (GTK_CONTAINER (alignment19), table8);
  gtk_container_set_border_width (GTK_CONTAINER (table8), 6);
  gtk_table_set_row_spacings (GTK_TABLE (table8), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table8), 6);

  checkbutton_emots = gtk_check_button_new_with_mnemonic ("U\305\274ywaj emotikon w oknie rozmowy");
  gtk_widget_set_name (checkbutton_emots, "checkbutton_emots");
  gtk_widget_show (checkbutton_emots);
  gtk_table_attach (GTK_TABLE (table8), checkbutton_emots, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label_emote_set = gtk_label_new ("Zestaw emotikon");
  gtk_widget_set_name (label_emote_set, "label_emote_set");
  gtk_widget_show (label_emote_set);
  gtk_table_attach (GTK_TABLE (table8), label_emote_set, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_emote_set), 0, 0.5);

  comboboxentry_emote_set = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (comboboxentry_emote_set, "comboboxentry_emote_set");
  gtk_widget_show (comboboxentry_emote_set);
  gtk_table_attach (GTK_TABLE (table8), comboboxentry_emote_set, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label58 = gtk_label_new ("<b>Emotikony</b>");
  gtk_widget_set_name (label58, "label58");
  gtk_widget_show (label58);
  gtk_frame_set_label_widget (GTK_FRAME (frame10), label58);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  label43 = gtk_label_new ("Okno rozmowy");
  gtk_widget_set_name (label43, "label43");
  gtk_widget_show (label43);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 2), label43);

  vbox8 = gtk_vbox_new (FALSE, 12);
  gtk_widget_set_name (vbox8, "vbox8");
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (notebook), vbox8);
  gtk_container_set_border_width (GTK_CONTAINER (vbox8), 12);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame8, "frame8");
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (vbox8), frame8, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame8), GTK_SHADOW_NONE);

  alignment17 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment17, "alignment17");
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (frame8), alignment17);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment17), 0, 0, 12, 0);

  table6 = gtk_table_new (4, 3, FALSE);
  gtk_widget_set_name (table6, "table6");
  gtk_widget_show (table6);
  gtk_container_add (GTK_CONTAINER (alignment17), table6);
  gtk_container_set_border_width (GTK_CONTAINER (table6), 6);
  gtk_table_set_row_spacings (GTK_TABLE (table6), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table6), 6);

  checkbutton_autoaway = gtk_check_button_new_with_mnemonic ("Automatycznie przechod\305\272 do stanu Zaraz wracam");
  gtk_widget_set_name (checkbutton_autoaway, "checkbutton_autoaway");
  gtk_widget_show (checkbutton_autoaway);
  gtk_table_attach (GTK_TABLE (table6), checkbutton_autoaway, 0, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label_aa2 = gtk_label_new ("Przej\305\233cie do stanu <i>Wr\303\263c\304\231 p\303\263\305\272niej</i> po");
  gtk_widget_set_name (label_aa2, "label_aa2");
  gtk_widget_show (label_aa2);
  gtk_table_attach (GTK_TABLE (table6), label_aa2, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label_aa2), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_aa2), 0, 0.5);

  spinbutton_away_time_adj = gtk_adjustment_new (1, 1, 999, 1, 10, 10);
  spinbutton_away_time = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_away_time_adj), 1, 0);
  gtk_widget_set_name (spinbutton_away_time, "spinbutton_away_time");
  gtk_widget_show (spinbutton_away_time);
  gtk_table_attach (GTK_TABLE (table6), spinbutton_away_time, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton_bbl_time_adj = gtk_adjustment_new (1, 1, 999, 1, 10, 10);
  spinbutton_bbl_time = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_bbl_time_adj), 1, 0);
  gtk_widget_set_name (spinbutton_bbl_time, "spinbutton_bbl_time");
  gtk_widget_show (spinbutton_bbl_time);
  gtk_table_attach (GTK_TABLE (table6), spinbutton_bbl_time, 1, 2, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label_aa11 = gtk_label_new ("minutach braku aktywno\305\233ci");
  gtk_widget_set_name (label_aa11, "label_aa11");
  gtk_widget_show (label_aa11);
  gtk_table_attach (GTK_TABLE (table6), label_aa11, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_aa11), 0, 0.5);

  label_aa1 = gtk_label_new ("Przej\305\233cie do stanu <i>Zaraz wracam</i> po");
  gtk_widget_set_name (label_aa1, "label_aa1");
  gtk_widget_show (label_aa1);
  gtk_table_attach (GTK_TABLE (table6), label_aa1, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label_aa1), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_aa1), 0, 0.5);

  label_aa22 = gtk_label_new ("minutach od <i>Zaraz wracam</i>");
  gtk_widget_set_name (label_aa22, "label_aa22");
  gtk_widget_show (label_aa22);
  gtk_table_attach (GTK_TABLE (table6), label_aa22, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label_aa22), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_aa22), 0, 0.5);

  checkbutton_autoaway_desc = gtk_check_button_new_with_mnemonic ("Dodawaj czas zmiany stanu do opisu");
  gtk_widget_set_name (checkbutton_autoaway_desc, "checkbutton_autoaway_desc");
  gtk_widget_show (checkbutton_autoaway_desc);
  gtk_table_attach (GTK_TABLE (table6), checkbutton_autoaway_desc, 0, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label50 = gtk_label_new ("<b>Automatyczna zmiana stanu</b>");
  gtk_widget_set_name (label50, "label50");
  gtk_widget_show (label50);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label50);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  frame9 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame9, "frame9");
  gtk_widget_show (frame9);
  gtk_box_pack_start (GTK_BOX (vbox8), frame9, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame9), GTK_SHADOW_NONE);

  alignment18 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment18, "alignment18");
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (frame9), alignment18);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment18), 0, 0, 12, 0);

  table9 = gtk_table_new (4, 2, FALSE);
  gtk_widget_set_name (table9, "table9");
  gtk_widget_show (table9);
  gtk_container_add (GTK_CONTAINER (alignment18), table9);
  gtk_container_set_border_width (GTK_CONTAINER (table9), 6);
  gtk_table_set_row_spacings (GTK_TABLE (table9), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table9), 6);

  radiobutton_start_status = gtk_radio_button_new_with_mnemonic (NULL, "Po uruchomieniu ustaw stan na:");
  gtk_widget_set_name (radiobutton_start_status, "radiobutton_start_status");
  gtk_widget_show (radiobutton_start_status);
  gtk_table_attach (GTK_TABLE (table9), radiobutton_start_status, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_start_status), radiobutton_start_status_group);
  radiobutton_start_status_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_start_status));

  comboboxentry_start_status = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (comboboxentry_start_status, "comboboxentry_start_status");
  gtk_widget_show (comboboxentry_start_status);
  gtk_table_attach (GTK_TABLE (table9), comboboxentry_start_status, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (comboboxentry_start_status, FALSE);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_start_status), "Dost\304\231pny");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_start_status), "Porozmawiajmy");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_start_status), "Jestem zaj\304\231ty");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_start_status), "Zaraz wracam");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_start_status), "Wr\303\263c\304\231 p\303\263\305\272niej");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_start_status), "Niewidoczny");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_start_status), "Niedost\304\231pny");

  radiobutton_status_save = gtk_radio_button_new_with_mnemonic (NULL, "Przywracaj stan ustawiony w momencie ostatniego wyj\305\233cia z programu");
  gtk_widget_set_name (radiobutton_status_save, "radiobutton_status_save");
  gtk_widget_show (radiobutton_status_save);
  gtk_table_attach (GTK_TABLE (table9), radiobutton_status_save, 0, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_status_save), radiobutton_start_status_group);
  radiobutton_start_status_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_status_save));

  checkbutton_desc_save = gtk_check_button_new_with_mnemonic ("Przywracaj opis ustawiony w momencie ostatniego wyj\305\233cia z programu");
  gtk_widget_set_name (checkbutton_desc_save, "checkbutton_desc_save");
  gtk_widget_show (checkbutton_desc_save);
  gtk_table_attach (GTK_TABLE (table9), checkbutton_desc_save, 0, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton_save_desc_at_exit = gtk_check_button_new_with_mnemonic ("Zostaw aktualny stan opisowy przy przej\305\233ciu w stan Niedost\304\231pny");
  gtk_widget_set_name (checkbutton_save_desc_at_exit, "checkbutton_save_desc_at_exit");
  gtk_widget_show (checkbutton_save_desc_at_exit);
  gtk_table_attach (GTK_TABLE (table9), checkbutton_save_desc_at_exit, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label57 = gtk_label_new ("<b>Zapisywanie stanu</b>");
  gtk_widget_set_name (label57, "label57");
  gtk_widget_show (label57);
  gtk_frame_set_label_widget (GTK_FRAME (frame9), label57);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);

  label44 = gtk_label_new ("Stan");
  gtk_widget_set_name (label44, "label44");
  gtk_widget_show (label44);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 3), label44);

  vbox10 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox10, "vbox10");
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (notebook), vbox10);
  gtk_container_set_border_width (GTK_CONTAINER (vbox10), 12);

  hbox188 = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox188, "hbox188");
  gtk_widget_show (hbox188);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox188, FALSE, TRUE, 0);

  label60 = gtk_label_new ("Polecenie uruchamiaj\304\205ce przegl\304\205dark\304\231 WWW:");
  gtk_widget_set_name (label60, "label60");
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox188), label60, FALSE, FALSE, 0);

  entry_browser = gtk_entry_new ();
  gtk_widget_set_name (entry_browser, "entry_browser");
  gtk_widget_show (entry_browser);
  gtk_box_pack_start (GTK_BOX (hbox188), entry_browser, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, entry_browser, "Wpisz polecenie przegl\304\205dark\304\231 za pomoc\304\205 kt\303\263rej chcesz otwiera\304\207 linki (np. 'mozilla %s'). Adres zostanie podstawiony w miejsce %s", NULL);

  label61 = gtk_label_new ("<span size=\"x-large\"><b>... opcje ...</b></span>");
  gtk_widget_set_name (label61, "label61");
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (vbox10), label61, TRUE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label61), TRUE);

  label45 = gtk_label_new ("Pozosta\305\202e");
  gtk_widget_set_name (label45, "label45");
  gtk_widget_show (label45);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 4), label45);

  hbox4 = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox4, FALSE, TRUE, 2);

  label_bottom = gtk_label_new ("");
  gtk_widget_set_name (label_bottom, "label_bottom");
  gtk_widget_show (label_bottom);
  gtk_box_pack_start (GTK_BOX (hbox4), label_bottom, TRUE, FALSE, 0);

  button_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (button_cancel, "button_cancel");
  gtk_widget_show (button_cancel);
  gtk_box_pack_start (GTK_BOX (hbox4), button_cancel, FALSE, FALSE, 0);

  button_accept = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (button_accept, "button_accept");
  gtk_widget_show (button_accept);
  gtk_box_pack_start (GTK_BOX (hbox4), button_accept, FALSE, TRUE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_prefs, win_prefs, "win_prefs");
  GLADE_HOOKUP_OBJECT (win_prefs, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (win_prefs, notebook, "notebook");
  GLADE_HOOKUP_OBJECT (win_prefs, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (win_prefs, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (win_prefs, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (win_prefs, table5, "table5");
  GLADE_HOOKUP_OBJECT (win_prefs, label48, "label48");
  GLADE_HOOKUP_OBJECT (win_prefs, label47, "label47");
  GLADE_HOOKUP_OBJECT (win_prefs, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (win_prefs, entry_pass, "entry_pass");
  GLADE_HOOKUP_OBJECT (win_prefs, label46, "label46");
  GLADE_HOOKUP_OBJECT (win_prefs, label41, "label41");
  GLADE_HOOKUP_OBJECT (win_prefs, label49, "label49");
  GLADE_HOOKUP_OBJECT (win_prefs, label42, "label42");
  GLADE_HOOKUP_OBJECT (win_prefs, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (win_prefs, frame10, "frame10");
  GLADE_HOOKUP_OBJECT (win_prefs, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (win_prefs, table8, "table8");
  GLADE_HOOKUP_OBJECT (win_prefs, checkbutton_emots, "checkbutton_emots");
  GLADE_HOOKUP_OBJECT (win_prefs, label_emote_set, "label_emote_set");
  GLADE_HOOKUP_OBJECT (win_prefs, comboboxentry_emote_set, "comboboxentry_emote_set");
  GLADE_HOOKUP_OBJECT (win_prefs, label58, "label58");
  GLADE_HOOKUP_OBJECT (win_prefs, label43, "label43");
  GLADE_HOOKUP_OBJECT (win_prefs, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (win_prefs, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (win_prefs, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (win_prefs, table6, "table6");
  GLADE_HOOKUP_OBJECT (win_prefs, checkbutton_autoaway, "checkbutton_autoaway");
  GLADE_HOOKUP_OBJECT (win_prefs, label_aa2, "label_aa2");
  GLADE_HOOKUP_OBJECT (win_prefs, spinbutton_away_time, "spinbutton_away_time");
  GLADE_HOOKUP_OBJECT (win_prefs, spinbutton_bbl_time, "spinbutton_bbl_time");
  GLADE_HOOKUP_OBJECT (win_prefs, label_aa11, "label_aa11");
  GLADE_HOOKUP_OBJECT (win_prefs, label_aa1, "label_aa1");
  GLADE_HOOKUP_OBJECT (win_prefs, label_aa22, "label_aa22");
  GLADE_HOOKUP_OBJECT (win_prefs, checkbutton_autoaway_desc, "checkbutton_autoaway_desc");
  GLADE_HOOKUP_OBJECT (win_prefs, label50, "label50");
  GLADE_HOOKUP_OBJECT (win_prefs, frame9, "frame9");
  GLADE_HOOKUP_OBJECT (win_prefs, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (win_prefs, table9, "table9");
  GLADE_HOOKUP_OBJECT (win_prefs, radiobutton_start_status, "radiobutton_start_status");
  GLADE_HOOKUP_OBJECT (win_prefs, comboboxentry_start_status, "comboboxentry_start_status");
  GLADE_HOOKUP_OBJECT (win_prefs, radiobutton_status_save, "radiobutton_status_save");
  GLADE_HOOKUP_OBJECT (win_prefs, checkbutton_desc_save, "checkbutton_desc_save");
  GLADE_HOOKUP_OBJECT (win_prefs, checkbutton_save_desc_at_exit, "checkbutton_save_desc_at_exit");
  GLADE_HOOKUP_OBJECT (win_prefs, label57, "label57");
  GLADE_HOOKUP_OBJECT (win_prefs, label44, "label44");
  GLADE_HOOKUP_OBJECT (win_prefs, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (win_prefs, hbox188, "hbox188");
  GLADE_HOOKUP_OBJECT (win_prefs, label60, "label60");
  GLADE_HOOKUP_OBJECT (win_prefs, entry_browser, "entry_browser");
  GLADE_HOOKUP_OBJECT (win_prefs, label61, "label61");
  GLADE_HOOKUP_OBJECT (win_prefs, label45, "label45");
  GLADE_HOOKUP_OBJECT (win_prefs, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (win_prefs, label_bottom, "label_bottom");
  GLADE_HOOKUP_OBJECT (win_prefs, button_cancel, "button_cancel");
  GLADE_HOOKUP_OBJECT (win_prefs, button_accept, "button_accept");
  GLADE_HOOKUP_OBJECT_NO_REF (win_prefs, tooltips, "tooltips");

  return win_prefs;
}

GtkWidget*
create_win_desc (void)
{
  GtkWidget *win_desc;
  GdkPixbuf *win_desc_icon_pixbuf;
  GtkWidget *vbox_main;
  GtkWidget *hbox_top;
  GtkWidget *vbox_top_left;
  GtkWidget *frame_stan;
  GtkWidget *alignment2;
  GtkWidget *table_stan;
  GtkWidget *radio_chatty;
  GSList *radio_chatty_group = NULL;
  GtkWidget *radio_away;
  GtkWidget *radio_bbl;
  GtkWidget *radio_avail;
  GtkWidget *radio_dnd;
  GtkWidget *radio_invisible;
  GtkWidget *radio_unavail;
  GtkWidget *label3;
  GtkWidget *table4;
  GtkWidget *entry2;
  GtkWidget *image_status;
  GtkWidget *label31;
  GtkWidget *entry_desc;
  GtkWidget *label32;
  GtkWidget *vseparator1;
  GtkWidget *vbox_top_right;
  GtkWidget *label4;
  GtkWidget *desc_scroll;
  GtkWidget *desc_tree;
  GtkWidget *hseparator3;
  GtkWidget *hbox_buttons;
  GtkWidget *btn_dodaj;
  GtkWidget *alignment7;
  GtkWidget *hbox15;
  GtkWidget *image14;
  GtkWidget *label11;
  GtkWidget *btn_zmien;
  GtkWidget *alignment6;
  GtkWidget *hbox14;
  GtkWidget *image13;
  GtkWidget *label10;
  GtkWidget *btn_usun;
  GtkWidget *alignment5;
  GtkWidget *hbox13;
  GtkWidget *image12;
  GtkWidget *label9;
  GtkWidget *spejs;
  GtkWidget *btn_anuluj;
  GtkWidget *alignment4;
  GtkWidget *hbox12;
  GtkWidget *image11;
  GtkWidget *label8;
  GtkWidget *btn_ustaw;
  GtkWidget *alignment3;
  GtkWidget *hbox11;
  GtkWidget *image10;
  GtkWidget *label7;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_desc = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_desc, "win_desc");
  gtk_container_set_border_width (GTK_CONTAINER (win_desc), 12);
  gtk_window_set_title (GTK_WINDOW (win_desc), "Stan opisowy");
  gtk_window_set_position (GTK_WINDOW (win_desc), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (win_desc), FALSE);
  win_desc_icon_pixbuf = create_pixbuf ("glen/status-avail.png");
  if (win_desc_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (win_desc), win_desc_icon_pixbuf);
      gdk_pixbuf_unref (win_desc_icon_pixbuf);
    }
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (win_desc), TRUE);

  vbox_main = gtk_vbox_new (FALSE, 12);
  gtk_widget_set_name (vbox_main, "vbox_main");
  gtk_widget_show (vbox_main);
  gtk_container_add (GTK_CONTAINER (win_desc), vbox_main);

  hbox_top = gtk_hbox_new (FALSE, 12);
  gtk_widget_set_name (hbox_top, "hbox_top");
  gtk_widget_show (hbox_top);
  gtk_box_pack_start (GTK_BOX (vbox_main), hbox_top, TRUE, TRUE, 0);

  vbox_top_left = gtk_vbox_new (FALSE, 12);
  gtk_widget_set_name (vbox_top_left, "vbox_top_left");
  gtk_widget_show (vbox_top_left);
  gtk_box_pack_start (GTK_BOX (hbox_top), vbox_top_left, TRUE, TRUE, 0);

  frame_stan = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_stan, "frame_stan");
  gtk_widget_show (frame_stan);
  gtk_box_pack_start (GTK_BOX (vbox_top_left), frame_stan, TRUE, TRUE, 0);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame_stan), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 10, 10);

  table_stan = gtk_table_new (4, 2, FALSE);
  gtk_widget_set_name (table_stan, "table_stan");
  gtk_widget_show (table_stan);
  gtk_container_add (GTK_CONTAINER (alignment2), table_stan);
  gtk_container_set_border_width (GTK_CONTAINER (table_stan), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table_stan), 24);

  radio_chatty = gtk_radio_button_new_with_mnemonic (NULL, "Porozmawiajmy");
  gtk_widget_set_name (radio_chatty, "radio_chatty");
  gtk_widget_show (radio_chatty);
  gtk_table_attach (GTK_TABLE (table_stan), radio_chatty, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (radio_chatty), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_chatty), radio_chatty_group);
  radio_chatty_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_chatty));

  radio_away = gtk_radio_button_new_with_mnemonic (NULL, "Zaraz wracam");
  gtk_widget_set_name (radio_away, "radio_away");
  gtk_widget_show (radio_away);
  gtk_table_attach (GTK_TABLE (table_stan), radio_away, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (radio_away), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_away), radio_chatty_group);
  radio_chatty_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_away));

  radio_bbl = gtk_radio_button_new_with_mnemonic (NULL, "Wr\303\263c\304\231 p\303\263\305\272niej");
  gtk_widget_set_name (radio_bbl, "radio_bbl");
  gtk_widget_show (radio_bbl);
  gtk_table_attach (GTK_TABLE (table_stan), radio_bbl, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (radio_bbl), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_bbl), radio_chatty_group);
  radio_chatty_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_bbl));

  radio_avail = gtk_radio_button_new_with_mnemonic (NULL, "Dost\304\231pny");
  gtk_widget_set_name (radio_avail, "radio_avail");
  gtk_widget_show (radio_avail);
  gtk_table_attach (GTK_TABLE (table_stan), radio_avail, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (radio_avail), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_avail), radio_chatty_group);
  radio_chatty_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_avail));

  radio_dnd = gtk_radio_button_new_with_mnemonic (NULL, "Jestem zaj\304\231ty");
  gtk_widget_set_name (radio_dnd, "radio_dnd");
  gtk_widget_show (radio_dnd);
  gtk_table_attach (GTK_TABLE (table_stan), radio_dnd, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (radio_dnd), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_dnd), radio_chatty_group);
  radio_chatty_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_dnd));

  radio_invisible = gtk_radio_button_new_with_mnemonic (NULL, "Niewidoczny");
  gtk_widget_set_name (radio_invisible, "radio_invisible");
  gtk_widget_show (radio_invisible);
  gtk_table_attach (GTK_TABLE (table_stan), radio_invisible, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (radio_invisible), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_invisible), radio_chatty_group);
  radio_chatty_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_invisible));

  radio_unavail = gtk_radio_button_new_with_mnemonic (NULL, "Niedost\304\231pny");
  gtk_widget_set_name (radio_unavail, "radio_unavail");
  gtk_widget_show (radio_unavail);
  gtk_table_attach (GTK_TABLE (table_stan), radio_unavail, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (radio_unavail), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_unavail), radio_chatty_group);
  radio_chatty_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_unavail));

  label3 = gtk_label_new ("<b>Rodzaj stanu</b>");
  gtk_widget_set_name (label3, "label3");
  gtk_widget_show (label3);
  gtk_frame_set_label_widget (GTK_FRAME (frame_stan), label3);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  table4 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table4, "table4");
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (vbox_top_left), table4, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 12);

  entry2 = gtk_entry_new ();
  gtk_widget_set_name (entry2, "entry2");
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table4), entry2, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (entry2, FALSE);

  image_status = create_pixmap (win_desc, "glen/status-avail.png");
  gtk_widget_set_name (image_status, "image_status");
  gtk_widget_show (image_status);
  gtk_table_attach (GTK_TABLE (table4), image_status, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label31 = gtk_label_new ("Opis:");
  gtk_widget_set_name (label31, "label31");
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table4), label31, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  entry_desc = gtk_entry_new ();
  gtk_widget_set_name (entry_desc, "entry_desc");
  gtk_widget_show (entry_desc);
  gtk_table_attach (GTK_TABLE (table4), entry_desc, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_entry_set_activates_default (GTK_ENTRY (entry_desc), TRUE);

  label32 = gtk_label_new ("Nazwa na li\305\233cie:");
  gtk_widget_set_name (label32, "label32");
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table4), label32, 0, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_set_name (vseparator1, "vseparator1");
  gtk_widget_show (vseparator1);
  gtk_box_pack_start (GTK_BOX (hbox_top), vseparator1, TRUE, TRUE, 0);

  vbox_top_right = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox_top_right, "vbox_top_right");
  gtk_widget_show (vbox_top_right);
  gtk_box_pack_start (GTK_BOX (hbox_top), vbox_top_right, FALSE, TRUE, 0);
  gtk_widget_set_size_request (vbox_top_right, 142, -1);

  label4 = gtk_label_new ("Lista stan\303\263w");
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox_top_right), label4, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  desc_scroll = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (desc_scroll, "desc_scroll");
  gtk_widget_show (desc_scroll);
  gtk_box_pack_start (GTK_BOX (vbox_top_right), desc_scroll, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (desc_scroll), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (desc_scroll), GTK_SHADOW_IN);

  desc_tree = gtk_tree_view_new ();
  gtk_widget_set_name (desc_tree, "desc_tree");
  gtk_widget_show (desc_tree);
  gtk_container_add (GTK_CONTAINER (desc_scroll), desc_tree);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (desc_tree), FALSE);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator3, "hseparator3");
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox_main), hseparator3, TRUE, TRUE, 0);

  hbox_buttons = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox_buttons, "hbox_buttons");
  gtk_widget_show (hbox_buttons);
  gtk_box_pack_start (GTK_BOX (vbox_main), hbox_buttons, TRUE, TRUE, 0);

  btn_dodaj = gtk_button_new ();
  gtk_widget_set_name (btn_dodaj, "btn_dodaj");
  gtk_widget_show (btn_dodaj);
  gtk_box_pack_start (GTK_BOX (hbox_buttons), btn_dodaj, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (btn_dodaj, FALSE);
  gtk_tooltips_set_tip (tooltips, btn_dodaj, "Wprowad\305\272 nazw\304\231 stanu i kliknij aby doda\304\207 go do listy", NULL);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment7, "alignment7");
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (btn_dodaj), alignment7);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox15, "hbox15");
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox15);

  image14 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image14, "image14");
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox15), image14, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic ("Dodaj");
  gtk_widget_set_name (label11, "label11");
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox15), label11, FALSE, FALSE, 0);

  btn_zmien = gtk_button_new ();
  gtk_widget_set_name (btn_zmien, "btn_zmien");
  gtk_widget_show (btn_zmien);
  gtk_box_pack_start (GTK_BOX (hbox_buttons), btn_zmien, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (btn_zmien, FALSE);
  gtk_tooltips_set_tip (tooltips, btn_zmien, "Wprowad\305\272 nazw\304\231 istniej\304\205cego stanu i kliknij, aby zmieni\304\207 odpowiadaj\304\205cy mu opis", NULL);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment6, "alignment6");
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btn_zmien), alignment6);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox14, "hbox14");
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox14);

  image13 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image13, "image13");
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox14), image13, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic ("Zmie\305\204");
  gtk_widget_set_name (label10, "label10");
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox14), label10, FALSE, FALSE, 0);

  btn_usun = gtk_button_new ();
  gtk_widget_set_name (btn_usun, "btn_usun");
  gtk_widget_show (btn_usun);
  gtk_box_pack_start (GTK_BOX (hbox_buttons), btn_usun, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (btn_usun, FALSE);
  gtk_tooltips_set_tip (tooltips, btn_usun, "Usu\305\204 zaznaczony stan", NULL);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment5, "alignment5");
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (btn_usun), alignment5);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox13, "hbox13");
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox13);

  image12 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image12, "image12");
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox13), image12, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic ("Usu\305\204");
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox13), label9, FALSE, FALSE, 0);

  spejs = gtk_label_new ("");
  gtk_widget_set_name (spejs, "spejs");
  gtk_widget_show (spejs);
  gtk_box_pack_start (GTK_BOX (hbox_buttons), spejs, TRUE, TRUE, 0);

  btn_anuluj = gtk_button_new ();
  gtk_widget_set_name (btn_anuluj, "btn_anuluj");
  gtk_widget_show (btn_anuluj);
  gtk_box_pack_start (GTK_BOX (hbox_buttons), btn_anuluj, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, btn_anuluj, "Anuluj zmian\304\231 stanu", NULL);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment4, "alignment4");
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (btn_anuluj), alignment4);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox12, "hbox12");
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox12);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image11, "image11");
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox12), image11, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic ("Anuluj");
  gtk_widget_set_name (label8, "label8");
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox12), label8, FALSE, FALSE, 0);

  btn_ustaw = gtk_button_new ();
  gtk_widget_set_name (btn_ustaw, "btn_ustaw");
  gtk_widget_show (btn_ustaw);
  gtk_box_pack_start (GTK_BOX (hbox_buttons), btn_ustaw, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (btn_ustaw, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, btn_ustaw, "Ustaw wybrany stan", NULL);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment3, "alignment3");
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (btn_ustaw), alignment3);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox11, "hbox11");
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox11);

  image10 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image10, "image10");
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox11), image10, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic ("Ustaw stan");
  gtk_widget_set_name (label7, "label7");
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox11), label7, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_desc, win_desc, "win_desc");
  GLADE_HOOKUP_OBJECT (win_desc, vbox_main, "vbox_main");
  GLADE_HOOKUP_OBJECT (win_desc, hbox_top, "hbox_top");
  GLADE_HOOKUP_OBJECT (win_desc, vbox_top_left, "vbox_top_left");
  GLADE_HOOKUP_OBJECT (win_desc, frame_stan, "frame_stan");
  GLADE_HOOKUP_OBJECT (win_desc, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (win_desc, table_stan, "table_stan");
  GLADE_HOOKUP_OBJECT (win_desc, radio_chatty, "radio_chatty");
  GLADE_HOOKUP_OBJECT (win_desc, radio_away, "radio_away");
  GLADE_HOOKUP_OBJECT (win_desc, radio_bbl, "radio_bbl");
  GLADE_HOOKUP_OBJECT (win_desc, radio_avail, "radio_avail");
  GLADE_HOOKUP_OBJECT (win_desc, radio_dnd, "radio_dnd");
  GLADE_HOOKUP_OBJECT (win_desc, radio_invisible, "radio_invisible");
  GLADE_HOOKUP_OBJECT (win_desc, radio_unavail, "radio_unavail");
  GLADE_HOOKUP_OBJECT (win_desc, label3, "label3");
  GLADE_HOOKUP_OBJECT (win_desc, table4, "table4");
  GLADE_HOOKUP_OBJECT (win_desc, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (win_desc, image_status, "image_status");
  GLADE_HOOKUP_OBJECT (win_desc, label31, "label31");
  GLADE_HOOKUP_OBJECT (win_desc, entry_desc, "entry_desc");
  GLADE_HOOKUP_OBJECT (win_desc, label32, "label32");
  GLADE_HOOKUP_OBJECT (win_desc, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (win_desc, vbox_top_right, "vbox_top_right");
  GLADE_HOOKUP_OBJECT (win_desc, label4, "label4");
  GLADE_HOOKUP_OBJECT (win_desc, desc_scroll, "desc_scroll");
  GLADE_HOOKUP_OBJECT (win_desc, desc_tree, "desc_tree");
  GLADE_HOOKUP_OBJECT (win_desc, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (win_desc, hbox_buttons, "hbox_buttons");
  GLADE_HOOKUP_OBJECT (win_desc, btn_dodaj, "btn_dodaj");
  GLADE_HOOKUP_OBJECT (win_desc, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (win_desc, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (win_desc, image14, "image14");
  GLADE_HOOKUP_OBJECT (win_desc, label11, "label11");
  GLADE_HOOKUP_OBJECT (win_desc, btn_zmien, "btn_zmien");
  GLADE_HOOKUP_OBJECT (win_desc, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (win_desc, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (win_desc, image13, "image13");
  GLADE_HOOKUP_OBJECT (win_desc, label10, "label10");
  GLADE_HOOKUP_OBJECT (win_desc, btn_usun, "btn_usun");
  GLADE_HOOKUP_OBJECT (win_desc, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (win_desc, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (win_desc, image12, "image12");
  GLADE_HOOKUP_OBJECT (win_desc, label9, "label9");
  GLADE_HOOKUP_OBJECT (win_desc, spejs, "spejs");
  GLADE_HOOKUP_OBJECT (win_desc, btn_anuluj, "btn_anuluj");
  GLADE_HOOKUP_OBJECT (win_desc, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (win_desc, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (win_desc, image11, "image11");
  GLADE_HOOKUP_OBJECT (win_desc, label8, "label8");
  GLADE_HOOKUP_OBJECT (win_desc, btn_ustaw, "btn_ustaw");
  GLADE_HOOKUP_OBJECT (win_desc, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (win_desc, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (win_desc, image10, "image10");
  GLADE_HOOKUP_OBJECT (win_desc, label7, "label7");
  GLADE_HOOKUP_OBJECT_NO_REF (win_desc, tooltips, "tooltips");

  gtk_widget_grab_default (btn_ustaw);
  return win_desc;
}

GtkWidget*
create_win_conf_wizard (void)
{
  GtkWidget *win_conf_wizard;
  GtkWidget *druid1;
  GtkWidget *druidpagestart1;
  GdkPixbuf *tmp_pixbuf;
  GtkWidget *page_konto;
  GtkWidget *druid_vbox1;
  GtkWidget *vbox3;
  GtkWidget *label12;
  GtkWidget *hbox16;
  GtkWidget *label13;
  GtkWidget *entry_login;
  GtkWidget *hbox17;
  GtkWidget *label15;
  GtkWidget *entry_pass;
  GtkWidget *druidpagefinish1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_conf_wizard = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_conf_wizard, "win_conf_wizard");
  gtk_window_set_title (GTK_WINDOW (win_conf_wizard), "Druid konfiguracji glena");

  druid1 = gnome_druid_new ();
  gtk_widget_set_name (druid1, "druid1");
  gtk_widget_show (druid1);
  gtk_container_add (GTK_CONTAINER (win_conf_wizard), druid1);
  gtk_container_set_border_width (GTK_CONTAINER (druid1), 4);

  druidpagestart1 = gnome_druid_page_edge_new (GNOME_EDGE_START);
  gtk_widget_set_name (druidpagestart1, "druidpagestart1");
  gtk_widget_show (druidpagestart1);
  gnome_druid_append_page (GNOME_DRUID (druid1),
                           GNOME_DRUID_PAGE (druidpagestart1));
  gnome_druid_page_edge_set_title (GNOME_DRUID_PAGE_EDGE (druidpagestart1), "Witaj w glenie");
  gnome_druid_page_edge_set_text (GNOME_DRUID_PAGE_EDGE (druidpagestart1), "Wygl\304\205da na to, \305\274e uruchomi\305\202e\305\233 glena po raz pierwszy. Ten druid pomo\305\274e Ci ustawi\304\207 podstawowe parametry programu.");
  tmp_pixbuf = create_pixbuf ("glen/status-avail.png");
  if (tmp_pixbuf)
    {
      gnome_druid_page_edge_set_logo (GNOME_DRUID_PAGE_EDGE (druidpagestart1),
                                      tmp_pixbuf);
      gdk_pixbuf_unref (tmp_pixbuf);
    }

  page_konto = gnome_druid_page_standard_new ();
  gtk_widget_set_name (page_konto, "page_konto");
  gtk_widget_show_all (page_konto);
  gnome_druid_append_page (GNOME_DRUID (druid1),
                           GNOME_DRUID_PAGE (page_konto));
  gnome_druid_page_standard_set_title (GNOME_DRUID_PAGE_STANDARD (page_konto), "Dane konta Tlen.pl");
  tmp_pixbuf = create_pixbuf ("glen/status-avail.png");
  if (tmp_pixbuf)
    {
      gnome_druid_page_standard_set_logo (GNOME_DRUID_PAGE_STANDARD (page_konto),
                                          tmp_pixbuf);
      gdk_pixbuf_unref (tmp_pixbuf);
    }

  druid_vbox1 = GNOME_DRUID_PAGE_STANDARD (page_konto)->vbox;
  gtk_widget_set_name (druid_vbox1, "druid_vbox1");
  gtk_widget_show (druid_vbox1);
  gtk_container_set_border_width (GTK_CONTAINER (druid_vbox1), 16);

  vbox3 = gtk_vbox_new (FALSE, 10);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (druid_vbox1), vbox3, TRUE, TRUE, 0);

  label12 = gtk_label_new ("Musisz mie\304\207 istniej\304\205ce konto w sieci Tlen.pl aby rozpocz\304\205\304\207 prac\304\231. Wpisz dane konta w poni\305\274szych polach.");
  gtk_widget_set_name (label12, "label12");
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (vbox3), label12, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label12, -1, 80);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label12), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  hbox16 = gtk_hbox_new (FALSE, 10);
  gtk_widget_set_name (hbox16, "hbox16");
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox16, TRUE, TRUE, 0);

  label13 = gtk_label_new ("Identyfikator: ");
  gtk_widget_set_name (label13, "label13");
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox16), label13, FALSE, TRUE, 0);
  gtk_widget_set_size_request (label13, 100, -1);

  entry_login = gtk_entry_new ();
  gtk_widget_set_name (entry_login, "entry_login");
  gtk_widget_show (entry_login);
  gtk_box_pack_start (GTK_BOX (hbox16), entry_login, FALSE, TRUE, 0);
  gtk_widget_set_size_request (entry_login, 200, -1);
  gtk_tooltips_set_tip (tooltips, entry_login, "Tw\303\263j login w sieci Tlen.pl, w formie nazwa@tlen.pl, nazwa@o2.pl lub po prostu nazwa", NULL);

  hbox17 = gtk_hbox_new (FALSE, 10);
  gtk_widget_set_name (hbox17, "hbox17");
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox17, TRUE, TRUE, 0);

  label15 = gtk_label_new ("Has\305\202o: ");
  gtk_widget_set_name (label15, "label15");
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox17), label15, FALSE, TRUE, 0);
  gtk_widget_set_size_request (label15, 100, -1);

  entry_pass = gtk_entry_new ();
  gtk_widget_set_name (entry_pass, "entry_pass");
  gtk_widget_show (entry_pass);
  gtk_box_pack_start (GTK_BOX (hbox17), entry_pass, FALSE, TRUE, 0);
  gtk_widget_set_size_request (entry_pass, 200, -1);
  gtk_tooltips_set_tip (tooltips, entry_pass, "Twoje has\305\202o w sieci Tlen.pl", NULL);
  gtk_entry_set_visibility (GTK_ENTRY (entry_pass), FALSE);

  druidpagefinish1 = gnome_druid_page_edge_new (GNOME_EDGE_FINISH);
  gtk_widget_set_name (druidpagefinish1, "druidpagefinish1");
  gtk_widget_show (druidpagefinish1);
  gnome_druid_append_page (GNOME_DRUID (druid1),
                           GNOME_DRUID_PAGE (druidpagefinish1));
  gnome_druid_page_edge_set_title (GNOME_DRUID_PAGE_EDGE (druidpagefinish1), "Konfiguracja zako\305\204czona");
  gnome_druid_page_edge_set_text (GNOME_DRUID_PAGE_EDGE (druidpagefinish1), "Podstawowa konfiguracja zako\305\204czona. Wi\304\231cej opcji znajdziesz w menu dost\304\231pnym z g\305\202\303\263wnego okna programu. Przyjemnych pogaduszek :)");
  tmp_pixbuf = create_pixbuf ("glen/status-avail.png");
  if (tmp_pixbuf)
    {
      gnome_druid_page_edge_set_logo (GNOME_DRUID_PAGE_EDGE (druidpagefinish1),
                                      tmp_pixbuf);
      gdk_pixbuf_unref (tmp_pixbuf);
    }

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_conf_wizard, win_conf_wizard, "win_conf_wizard");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, druid1, "druid1");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, druidpagestart1, "druidpagestart1");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, page_konto, "page_konto");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, druid_vbox1, "druid_vbox1");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, label12, "label12");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, label13, "label13");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, entry_login, "entry_login");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, label15, "label15");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, entry_pass, "entry_pass");
  GLADE_HOOKUP_OBJECT (win_conf_wizard, druidpagefinish1, "druidpagefinish1");
  GLADE_HOOKUP_OBJECT_NO_REF (win_conf_wizard, tooltips, "tooltips");

  return win_conf_wizard;
}

GtkWidget*
create_win_msg_send (void)
{
  GtkWidget *win_msg_send;
  GdkPixbuf *win_msg_send_icon_pixbuf;
  GtkWidget *vbox4;
  GtkWidget *label_to;
  GtkWidget *hseparator4;
  GtkWidget *scrolledwindow2;
  GtkWidget *text;
  GtkWidget *hbox184;
  GtkWidget *space;
  GtkWidget *button_close;
  GtkWidget *button_send;
  GtkWidget *alignment12;
  GtkWidget *hbox185;
  GtkWidget *image17;
  GtkWidget *label30;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_msg_send = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_msg_send, "win_msg_send");
  gtk_container_set_border_width (GTK_CONTAINER (win_msg_send), 12);
  gtk_window_set_title (GTK_WINDOW (win_msg_send), "Nowa wiadomo\305\233\304\207");
  gtk_window_set_resizable (GTK_WINDOW (win_msg_send), FALSE);
  win_msg_send_icon_pixbuf = create_pixbuf ("glen/status-avail.png");
  if (win_msg_send_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (win_msg_send), win_msg_send_icon_pixbuf);
      gdk_pixbuf_unref (win_msg_send_icon_pixbuf);
    }

  vbox4 = gtk_vbox_new (FALSE, 12);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (win_msg_send), vbox4);

  label_to = gtk_label_new ("label16");
  gtk_widget_set_name (label_to, "label_to");
  gtk_widget_show (label_to);
  gtk_box_pack_start (GTK_BOX (vbox4), label_to, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label_to), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_to), 0, 0.5);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator4, "hseparator4");
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (vbox4), hseparator4, TRUE, TRUE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow2, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindow2, 320, 200);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  text = gtk_text_view_new ();
  gtk_widget_set_name (text, "text");
  gtk_widget_show (text);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), text);
  gtk_tooltips_set_tip (tooltips, text, "Wprowad\305\272 tekst wiadomo\305\233ci do wys\305\202ania", NULL);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (text), GTK_WRAP_WORD);

  hbox184 = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox184, "hbox184");
  gtk_widget_show (hbox184);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox184, FALSE, TRUE, 0);

  space = gtk_label_new ("");
  gtk_widget_set_name (space, "space");
  gtk_widget_show (space);
  gtk_box_pack_start (GTK_BOX (hbox184), space, TRUE, FALSE, 0);

  button_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (button_close, "button_close");
  gtk_widget_show (button_close);
  gtk_box_pack_start (GTK_BOX (hbox184), button_close, FALSE, FALSE, 0);

  button_send = gtk_button_new ();
  gtk_widget_set_name (button_send, "button_send");
  gtk_widget_show (button_send);
  gtk_box_pack_start (GTK_BOX (hbox184), button_send, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, button_send, "Wysy\305\202a wiadomo\305\233\304\207", NULL);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment12, "alignment12");
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_send), alignment12);

  hbox185 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox185, "hbox185");
  gtk_widget_show (hbox185);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox185);

  image17 = gtk_image_new_from_stock ("gnome-stock-mail-snd", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image17, "image17");
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox185), image17, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic ("_Wy\305\233lij");
  gtk_widget_set_name (label30, "label30");
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox185), label30, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_msg_send, win_msg_send, "win_msg_send");
  GLADE_HOOKUP_OBJECT (win_msg_send, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (win_msg_send, label_to, "label_to");
  GLADE_HOOKUP_OBJECT (win_msg_send, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (win_msg_send, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (win_msg_send, text, "text");
  GLADE_HOOKUP_OBJECT (win_msg_send, hbox184, "hbox184");
  GLADE_HOOKUP_OBJECT (win_msg_send, space, "space");
  GLADE_HOOKUP_OBJECT (win_msg_send, button_close, "button_close");
  GLADE_HOOKUP_OBJECT (win_msg_send, button_send, "button_send");
  GLADE_HOOKUP_OBJECT (win_msg_send, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (win_msg_send, hbox185, "hbox185");
  GLADE_HOOKUP_OBJECT (win_msg_send, image17, "image17");
  GLADE_HOOKUP_OBJECT (win_msg_send, label30, "label30");
  GLADE_HOOKUP_OBJECT_NO_REF (win_msg_send, tooltips, "tooltips");

  return win_msg_send;
}

GtkWidget*
create_win_msg_recv (void)
{
  GtkWidget *win_msg_recv;
  GdkPixbuf *win_msg_recv_icon_pixbuf;
  GtkWidget *vbox5;
  GtkWidget *table1;
  GtkWidget *label21;
  GtkWidget *label20;
  GtkWidget *label_time;
  GtkWidget *button_next;
  GtkWidget *button_prev;
  GtkWidget *button_reply;
  GtkWidget *alignment10;
  GtkWidget *hbox19;
  GtkWidget *image16;
  GtkWidget *label24;
  GtkWidget *label_from;
  GtkWidget *hseparator2;
  GtkWidget *scroll_output;
  GtkWidget *hbox22;
  GtkWidget *label_count;
  GtkWidget *button_close;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_msg_recv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_msg_recv, "win_msg_recv");
  gtk_container_set_border_width (GTK_CONTAINER (win_msg_recv), 12);
  gtk_window_set_title (GTK_WINDOW (win_msg_recv), "Otrzymano wiadomo\305\233\304\207");
  gtk_window_set_resizable (GTK_WINDOW (win_msg_recv), FALSE);
  win_msg_recv_icon_pixbuf = create_pixbuf ("glen/status-avail.png");
  if (win_msg_recv_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (win_msg_recv), win_msg_recv_icon_pixbuf);
      gdk_pixbuf_unref (win_msg_recv_icon_pixbuf);
    }

  vbox5 = gtk_vbox_new (FALSE, 12);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (win_msg_recv), vbox5);

  table1 = gtk_table_new (2, 4, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox5), table1, FALSE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 6);

  label21 = gtk_label_new ("Otrzymano: ");
  gtk_widget_set_name (label21, "label21");
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table1), label21, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label20 = gtk_label_new ("Od: ");
  gtk_widget_set_name (label20, "label20");
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table1), label20, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label_time = gtk_label_new ("<b>time</b>");
  gtk_widget_set_name (label_time, "label_time");
  gtk_widget_show (label_time);
  gtk_table_attach (GTK_TABLE (table1), label_time, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label_time), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_time), 0, 0.5);

  button_next = gtk_button_new_from_stock ("gtk-media-next");
  gtk_widget_set_name (button_next, "button_next");
  gtk_widget_show (button_next);
  gtk_table_attach (GTK_TABLE (table1), button_next, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (button_next, FALSE);
  gtk_tooltips_set_tip (tooltips, button_next, "Przejd\305\272 do nast\304\231pnej wiadomo\305\233ci", NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (button_next), FALSE);

  button_prev = gtk_button_new_from_stock ("gtk-media-previous");
  gtk_widget_set_name (button_prev, "button_prev");
  gtk_widget_show (button_prev);
  gtk_table_attach (GTK_TABLE (table1), button_prev, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (button_prev, FALSE);
  gtk_tooltips_set_tip (tooltips, button_prev, "Przejd\305\272 do poprzedniej wiadomo\305\233ci", NULL);

  button_reply = gtk_button_new ();
  gtk_widget_set_name (button_reply, "button_reply");
  gtk_widget_show (button_reply);
  gtk_table_attach (GTK_TABLE (table1), button_reply, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, button_reply, "Odpowiedz nadawcy", NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (button_reply), FALSE);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment10, "alignment10");
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_reply), alignment10);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox19, "hbox19");
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox19);

  image16 = gtk_image_new_from_stock ("gnome-stock-mail-rpl", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image16, "image16");
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox19), image16, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic ("_Odpisz");
  gtk_widget_set_name (label24, "label24");
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox19), label24, FALSE, FALSE, 0);

  label_from = gtk_label_new ("<b>from</b>");
  gtk_widget_set_name (label_from, "label_from");
  gtk_widget_show (label_from);
  gtk_table_attach (GTK_TABLE (table1), label_from, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label_from), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_from), 0, 0.5);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator2, "hseparator2");
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox5), hseparator2, FALSE, FALSE, 0);

  scroll_output = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scroll_output, "scroll_output");
  gtk_widget_show (scroll_output);
  gtk_box_pack_start (GTK_BOX (vbox5), scroll_output, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scroll_output, 380, 200);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scroll_output), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scroll_output), GTK_SHADOW_ETCHED_IN);

  hbox22 = gtk_hbox_new (FALSE, 12);
  gtk_widget_set_name (hbox22, "hbox22");
  gtk_widget_show (hbox22);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox22, FALSE, TRUE, 0);

  label_count = gtk_label_new ("<b>Nieprzeczytanych: 0</b>");
  gtk_widget_set_name (label_count, "label_count");
  gtk_widget_show (label_count);
  gtk_box_pack_start (GTK_BOX (hbox22), label_count, TRUE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label_count), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_count), 0, 0.5);

  button_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (button_close, "button_close");
  gtk_widget_show (button_close);
  gtk_box_pack_start (GTK_BOX (hbox22), button_close, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, button_close, "Zamknij okno. Nieprzeczytane wiadomo\305\233ci mo\305\274esz odnale\305\272\304\207 w archiwum.", NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_msg_recv, win_msg_recv, "win_msg_recv");
  GLADE_HOOKUP_OBJECT (win_msg_recv, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (win_msg_recv, table1, "table1");
  GLADE_HOOKUP_OBJECT (win_msg_recv, label21, "label21");
  GLADE_HOOKUP_OBJECT (win_msg_recv, label20, "label20");
  GLADE_HOOKUP_OBJECT (win_msg_recv, label_time, "label_time");
  GLADE_HOOKUP_OBJECT (win_msg_recv, button_next, "button_next");
  GLADE_HOOKUP_OBJECT (win_msg_recv, button_prev, "button_prev");
  GLADE_HOOKUP_OBJECT (win_msg_recv, button_reply, "button_reply");
  GLADE_HOOKUP_OBJECT (win_msg_recv, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (win_msg_recv, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (win_msg_recv, image16, "image16");
  GLADE_HOOKUP_OBJECT (win_msg_recv, label24, "label24");
  GLADE_HOOKUP_OBJECT (win_msg_recv, label_from, "label_from");
  GLADE_HOOKUP_OBJECT (win_msg_recv, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (win_msg_recv, scroll_output, "scroll_output");
  GLADE_HOOKUP_OBJECT (win_msg_recv, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (win_msg_recv, label_count, "label_count");
  GLADE_HOOKUP_OBJECT (win_msg_recv, button_close, "button_close");
  GLADE_HOOKUP_OBJECT_NO_REF (win_msg_recv, tooltips, "tooltips");

  return win_msg_recv;
}

GtkWidget*
create_win_edit (void)
{
  GtkWidget *win_edit;
  GdkPixbuf *win_edit_icon_pixbuf;
  GtkWidget *vbox6;
  GtkWidget *frame4;
  GtkWidget *alignment13;
  GtkWidget *table2;
  GtkWidget *entry_id;
  GtkWidget *entry_name;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label36;
  GtkWidget *frame5;
  GtkWidget *alignment14;
  GtkWidget *table3;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *entry_phone;
  GtkWidget *combobox_group;
  GtkWidget *label37;
  GtkWidget *frame6;
  GtkWidget *alignment15;
  GtkWidget *scrolledwindow3;
  GtkWidget *textview_notes;
  GtkWidget *label38;
  GtkWidget *hseparator5;
  GtkWidget *hbox186;
  GtkWidget *space1;
  GtkWidget *button_cancel;
  GtkWidget *button_accept;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_edit = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_edit, "win_edit");
  gtk_container_set_border_width (GTK_CONTAINER (win_edit), 12);
  gtk_window_set_title (GTK_WINDOW (win_edit), "Edycja danych kontaktu");
  gtk_window_set_position (GTK_WINDOW (win_edit), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (win_edit), 400, 300);
  gtk_window_set_resizable (GTK_WINDOW (win_edit), FALSE);
  win_edit_icon_pixbuf = create_pixbuf ("glen/status-avail.png");
  if (win_edit_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (win_edit), win_edit_icon_pixbuf);
      gdk_pixbuf_unref (win_edit_icon_pixbuf);
    }

  vbox6 = gtk_vbox_new (FALSE, 12);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (win_edit), vbox6);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame4, "frame4");
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox6), frame4, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame4), GTK_SHADOW_NONE);

  alignment13 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment13, "alignment13");
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (frame4), alignment13);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment13), 0, 0, 12, 0);

  table2 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table2, "table2");
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (alignment13), table2);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 12);

  entry_id = gtk_entry_new ();
  gtk_widget_set_name (entry_id, "entry_id");
  gtk_widget_show (entry_id);
  gtk_table_attach (GTK_TABLE (table2), entry_id, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_id, 170, -1);
  GTK_WIDGET_SET_FLAGS (entry_id, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, entry_id, "Identyfikator kontaktu w systemie Tlen.pl, na przyk\305\202ad jasio@tlen.pl", NULL);

  entry_name = gtk_entry_new ();
  gtk_widget_set_name (entry_name, "entry_name");
  gtk_widget_show (entry_name);
  gtk_table_attach (GTK_TABLE (table2), entry_name, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_name, 170, -1);
  gtk_tooltips_set_tip (tooltips, entry_name, "Nazwa dla kontaktu widoczna na li\305\233cie.", NULL);

  label25 = gtk_label_new ("Identyfikator w systemie Tlen.pl:");
  gtk_widget_set_name (label25, "label25");
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table2), label25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label26 = gtk_label_new ("Na li\305\233cie wy\305\233wietli si\304\231:");
  gtk_widget_set_name (label26, "label26");
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table2), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label36 = gtk_label_new ("<b>Identyfikacja</b>");
  gtk_widget_set_name (label36, "label36");
  gtk_widget_show (label36);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label36);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame5, "frame5");
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (vbox6), frame5, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame5), GTK_SHADOW_NONE);

  alignment14 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment14, "alignment14");
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (frame5), alignment14);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment14), 0, 0, 12, 0);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table3, "table3");
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (alignment14), table3);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 12);

  label27 = gtk_label_new ("Grupa kontaktu");
  gtk_widget_set_name (label27, "label27");
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table3), label27, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label28 = gtk_label_new ("Numer telefonu kom\303\263rkowego");
  gtk_widget_set_name (label28, "label28");
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table3), label28, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (label28, FALSE);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  entry_phone = gtk_entry_new ();
  gtk_widget_set_name (entry_phone, "entry_phone");
  gtk_widget_show (entry_phone);
  gtk_table_attach (GTK_TABLE (table3), entry_phone, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_phone, 170, -1);
  gtk_widget_set_sensitive (entry_phone, FALSE);
  gtk_tooltips_set_tip (tooltips, entry_phone, "Numer telefonu kom\303\263rkowego tej osoby. Na razie do niczego si\304\231 nie przyda :)", NULL);

  combobox_group = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (combobox_group, "combobox_group");
  gtk_widget_show (combobox_group);
  gtk_table_attach (GTK_TABLE (table3), combobox_group, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_size_request (combobox_group, 170, -1);

  label37 = gtk_label_new ("<b>Pozosta\305\202e informacje</b>");
  gtk_widget_set_name (label37, "label37");
  gtk_widget_show (label37);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label37);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame6, "frame6");
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox6), frame6, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame6), GTK_SHADOW_NONE);

  alignment15 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment15, "alignment15");
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (frame6), alignment15);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment15), 0, 0, 12, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow3, "scrolledwindow3");
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (alignment15), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  textview_notes = gtk_text_view_new ();
  gtk_widget_set_name (textview_notes, "textview_notes");
  gtk_widget_show (textview_notes);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textview_notes);
  gtk_widget_set_sensitive (textview_notes, FALSE);

  label38 = gtk_label_new ("<b>Notatki</b>");
  gtk_widget_set_name (label38, "label38");
  gtk_widget_show (label38);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label38);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator5, "hseparator5");
  gtk_widget_show (hseparator5);
  gtk_box_pack_start (GTK_BOX (vbox6), hseparator5, TRUE, TRUE, 0);

  hbox186 = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox186, "hbox186");
  gtk_widget_show (hbox186);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox186, FALSE, TRUE, 0);

  space1 = gtk_label_new (" ");
  gtk_widget_set_name (space1, "space1");
  gtk_widget_show (space1);
  gtk_box_pack_start (GTK_BOX (hbox186), space1, TRUE, FALSE, 0);

  button_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (button_cancel, "button_cancel");
  gtk_widget_show (button_cancel);
  gtk_box_pack_start (GTK_BOX (hbox186), button_cancel, FALSE, FALSE, 0);

  button_accept = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (button_accept, "button_accept");
  gtk_widget_show (button_accept);
  gtk_box_pack_start (GTK_BOX (hbox186), button_accept, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button_accept, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_edit, win_edit, "win_edit");
  GLADE_HOOKUP_OBJECT (win_edit, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (win_edit, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (win_edit, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (win_edit, table2, "table2");
  GLADE_HOOKUP_OBJECT (win_edit, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (win_edit, entry_name, "entry_name");
  GLADE_HOOKUP_OBJECT (win_edit, label25, "label25");
  GLADE_HOOKUP_OBJECT (win_edit, label26, "label26");
  GLADE_HOOKUP_OBJECT (win_edit, label36, "label36");
  GLADE_HOOKUP_OBJECT (win_edit, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (win_edit, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (win_edit, table3, "table3");
  GLADE_HOOKUP_OBJECT (win_edit, label27, "label27");
  GLADE_HOOKUP_OBJECT (win_edit, label28, "label28");
  GLADE_HOOKUP_OBJECT (win_edit, entry_phone, "entry_phone");
  GLADE_HOOKUP_OBJECT (win_edit, combobox_group, "combobox_group");
  GLADE_HOOKUP_OBJECT (win_edit, label37, "label37");
  GLADE_HOOKUP_OBJECT (win_edit, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (win_edit, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (win_edit, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (win_edit, textview_notes, "textview_notes");
  GLADE_HOOKUP_OBJECT (win_edit, label38, "label38");
  GLADE_HOOKUP_OBJECT (win_edit, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (win_edit, hbox186, "hbox186");
  GLADE_HOOKUP_OBJECT (win_edit, space1, "space1");
  GLADE_HOOKUP_OBJECT (win_edit, button_cancel, "button_cancel");
  GLADE_HOOKUP_OBJECT (win_edit, button_accept, "button_accept");
  GLADE_HOOKUP_OBJECT_NO_REF (win_edit, tooltips, "tooltips");

  gtk_widget_grab_focus (entry_id);
  gtk_widget_grab_default (button_accept);
  return win_edit;
}

GtkWidget*
create_win_about (void)
{
  const gchar *authors[] = {
    "Krzysztof Godlewski <krzygod@gmail.com>",
    NULL
  };
  const gchar *documenters[] = { NULL };
  gchar *translators = NULL;
  GtkWidget *win_about;
  GdkPixbuf *win_about_icon_pixbuf;

  win_about = gnome_about_new ("glen", VERSION,
                        "\302\251 2005 Krzysztof Godlewski <krzygod@gmail.com>",
                        "Klient sieci Tlen.pl dla \305\233rodowiska Gnome",
                        authors,
                        documenters,
                        translators,
                        NULL);
  gtk_widget_set_name (win_about, "win_about");
  gtk_container_set_border_width (GTK_CONTAINER (win_about), 6);
  win_about_icon_pixbuf = create_pixbuf ("glen/status-avail.png");
  if (win_about_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (win_about), win_about_icon_pixbuf);
      gdk_pixbuf_unref (win_about_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (win_about), GDK_WINDOW_TYPE_HINT_DIALOG);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_about, win_about, "win_about");

  return win_about;
}

GtkWidget*
create_win_arch (void)
{
  GtkWidget *win_arch;
  GtkWidget *vbox11;
  GtkWidget *hbox_stuff;
  GtkWidget *scrolledwindow4;
  GtkWidget *tree_users;
  GtkWidget *vbox12;
  GtkWidget *scrolledwindow5;
  GtkWidget *tree_list;
  GtkWidget *scroll;
  GtkWidget *hbox190;
  GtkWidget *button_close;

  win_arch = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_arch, "win_arch");
  gtk_container_set_border_width (GTK_CONTAINER (win_arch), 12);
  gtk_window_set_title (GTK_WINDOW (win_arch), "Archiwum rozm\303\263w");
  gtk_window_set_default_size (GTK_WINDOW (win_arch), 600, 400);

  vbox11 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox11, "vbox11");
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (win_arch), vbox11);

  hbox_stuff = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox_stuff, "hbox_stuff");
  gtk_widget_show (hbox_stuff);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox_stuff, TRUE, TRUE, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow4, "scrolledwindow4");
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (hbox_stuff), scrolledwindow4, FALSE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_ETCHED_IN);

  tree_users = gtk_tree_view_new ();
  gtk_widget_set_name (tree_users, "tree_users");
  gtk_widget_show (tree_users);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), tree_users);
  gtk_widget_set_size_request (tree_users, 250, -1);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (tree_users), FALSE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (tree_users), TRUE);
  gtk_tree_view_set_fixed_height_mode (GTK_TREE_VIEW (tree_users), TRUE);

  vbox12 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox12, "vbox12");
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (hbox_stuff), vbox12, TRUE, TRUE, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow5, "scrolledwindow5");
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox12), scrolledwindow5, FALSE, FALSE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_ETCHED_IN);

  tree_list = gtk_tree_view_new ();
  gtk_widget_set_name (tree_list, "tree_list");
  gtk_widget_show (tree_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), tree_list);
  gtk_widget_set_size_request (tree_list, -1, 95);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (tree_list), FALSE);
  gtk_tree_view_set_fixed_height_mode (GTK_TREE_VIEW (tree_list), TRUE);

  scroll = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scroll, "scroll");
  gtk_widget_show (scroll);
  gtk_box_pack_start (GTK_BOX (vbox12), scroll, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scroll), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scroll), GTK_SHADOW_ETCHED_IN);

  hbox190 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox190, "hbox190");
  gtk_widget_show (hbox190);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox190, FALSE, FALSE, 0);

  button_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (button_close, "button_close");
  gtk_widget_show (button_close);
  gtk_box_pack_start (GTK_BOX (hbox190), button_close, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_arch, win_arch, "win_arch");
  GLADE_HOOKUP_OBJECT (win_arch, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (win_arch, hbox_stuff, "hbox_stuff");
  GLADE_HOOKUP_OBJECT (win_arch, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (win_arch, tree_users, "tree_users");
  GLADE_HOOKUP_OBJECT (win_arch, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (win_arch, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (win_arch, tree_list, "tree_list");
  GLADE_HOOKUP_OBJECT (win_arch, scroll, "scroll");
  GLADE_HOOKUP_OBJECT (win_arch, hbox190, "hbox190");
  GLADE_HOOKUP_OBJECT (win_arch, button_close, "button_close");

  return win_arch;
}

